In [1]:
import os 
import pandas as pd
import datetime
import numpy as np
import matplotlib.pyplot as plt
# import subprocess #ベクター画像出力用
import matplotlib.dates as mdates # DataTimeの横軸調整

In [2]:
csv_file_name = os.listdir('input')
csv_file_name

trigger_times = []
for filename in csv_file_name:
    filepath = 'input/' + filename
    print(filepath,type(filepath))
    df = pd.read_csv(filepath, names=range(32)) # 行によってカラム数が違うとエラーを吐くのでnamesで列名を指定する
    trigger_time = (df.loc[df.iloc[:,0] == "Trigger Time"]).iloc[0,1] # Trigger Timeの値を検索して代入
    trigger_time = trigger_time.replace("'", "20")
    trigger_time = trigger_time[0:19]
    dt_trigger_time = datetime.datetime.strptime(trigger_time, "%Y-%m-%d %H:%M:%S")
    trigger_times.append(dt_trigger_time)

def time_change(x):
    dt2 = dt1 + datetime.timedelta(seconds=x)
    return dt2

count = 0
for (filename,trigger_time) in zip(csv_file_name, trigger_times):
    count += 1
    filepath = 'input/' + filename
    df1 = pd.read_csv(filepath, header=11)
    dt1 = trigger_time
    df1['Time'] = df1['Time'].apply(time_change)
    df1 = df1.set_index('Time', drop=True) # 引数drop=Falseとすると、指定列がindexに設定された上でデータ列にもそのまま残る
    # print(df1)
    if count == 1:
        df = df1
    if count >= 2:
        df = pd.concat([df, df1])

df = df.resample('s').interpolate() # 線形補完
df = df.resample('10min').interpolate() # 線形補完

df = df.where(df <= 100, -10)

df = df.drop(df.columns[list(range(0,15))], axis=1) # 有線データの削除
df = df.drop(df.columns[-1], axis=1) # 有線データの削除
df.to_csv('output/temp.csv')
df

input/PoolTEMP_20221222.csv <class 'str'>
input/PoolTEMP_20221224.csv <class 'str'>
input/PoolTEMP_20230107.csv <class 'str'>

,R1-1[C],R1-2[C],R1-3[C],R1-4[C],R1-5[C],R1-6[C],R1-7[C],R1-8[C],R1-9[C],R1-10[C],R1-11[C],R1-12[C],R1-13[C],R1-14[C],R1-15[C]
Time,,,,,,,,,,,,,,,
2022-12-21 16:00:00,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000
2022-12-21 16:10:00,0.926667,0.655833,-0.705000,-0.803333,-0.497500,-0.137500,0.260833,0.552500,0.858333,1.064167,1.240000,1.538333,1.750000,1.986667,1.585000
2022-12-21 16:20:00,1.490833,1.092500,-0.457500,-0.735833,-0.451667,-0.100000,0.437500,0.598333,0.942500,1.061667,1.254167,1.551667,1.725833,2.140000,1.618333
2022-12-21 16:30:00,1.876667,1.380000,-0.309167,-0.695833,-0.379167,0.193333,0.840833,0.736667,1.130833,1.046667,1.235833,1.530000,1.704167,2.206667,1.685833
2022-12-21 16:40:00,1.443333,1.090000,-0.144167,-0.390000,-0.034167,0.728333,1.082500,0.915000,1.322500,1.088333,1.225833,1.511667,1.710000,2.268333,1.735833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-06 09:40:00,5.742667,5.819167,5.860000,6.069500,8.826500,9.054333,9.063500,9.040000,9.013500,8.990000,8.990000,8.987833,9.010000,9.000000,8.915667
2023-01-06 09:50:00,5.850833,5.969500,5.990000,6.200333,8.832167,9.042167,9.057833,9.002167,8.992167,8.962167,8.958667,8.970000,8.987833,8.984333,8.897833
2023-01-06 10:00:00,5.847333,5.903333,5.899833,6.064500,8.813500,9.010000,9.022167,8.987833,8.957833,8.947833,8.930000,8.947833,8.970000,8.957833,8.889167
2023-01-06 10:10:00,4.354833,4.391333,4.604500,5.160000,8.774333,9.017833,9.010000,8.981333,8.967833,8.957833,8.957833,8.942167,8.972167,8.970000,8.870000
2023-01-06 10:20:00,-0.025500,-0.060333,0.341833,0.972667,8.644333,8.870000,8.880000,8.840833,8.815167,8.810833,8.818667,8.806500,8.727833,8.380000,8.068667

In [3]:
df = pd.read_csv('output/temp.csv', header=0)
df = df.set_index("Time")
df

,R1-1[C],R1-2[C],R1-3[C],R1-4[C],R1-5[C],R1-6[C],R1-7[C],R1-8[C],R1-9[C],R1-10[C],R1-11[C],R1-12[C],R1-13[C],R1-14[C],R1-15[C]
Time,,,,,,,,,,,,,,,
2022-12-21 16:00:00,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000
2022-12-21 16:10:00,0.926667,0.655833,-0.705000,-0.803333,-0.497500,-0.137500,0.260833,0.552500,0.858333,1.064167,1.240000,1.538333,1.750000,1.986667,1.585000
2022-12-21 16:20:00,1.490833,1.092500,-0.457500,-0.735833,-0.451667,-0.100000,0.437500,0.598333,0.942500,1.061667,1.254167,1.551667,1.725833,2.140000,1.618333
2022-12-21 16:30:00,1.876667,1.380000,-0.309167,-0.695833,-0.379167,0.193333,0.840833,0.736667,1.130833,1.046667,1.235833,1.530000,1.704167,2.206667,1.685833
2022-12-21 16:40:00,1.443333,1.090000,-0.144167,-0.390000,-0.034167,0.728333,1.082500,0.915000,1.322500,1.088333,1.225833,1.511667,1.710000,2.268333,1.735833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-06 09:40:00,5.742667,5.819167,5.860000,6.069500,8.826500,9.054333,9.063500,9.040000,9.013500,8.990000,8.990000,8.987833,9.010000,9.000000,8.915667
2023-01-06 09:50:00,5.850833,5.969500,5.990000,6.200333,8.832167,9.042167,9.057833,9.002167,8.992167,8.962167,8.958667,8.970000,8.987833,8.984333,8.897833
2023-01-06 10:00:00,5.847333,5.903333,5.899833,6.064500,8.813500,9.010000,9.022167,8.987833,8.957833,8.947833,8.930000,8.947833,8.970000,8.957833,8.889167
2023-01-06 10:10:00,4.354833,4.391333,4.604500,5.160000,8.774333,9.017833,9.010000,8.981333,8.967833,8.957833,8.957833,8.942167,8.972167,8.970000,8.870000
2023-01-06 10:20:00,-0.025500,-0.060333,0.341833,0.972667,8.644333,8.870000,8.880000,8.840833,8.815167,8.810833,8.818667,8.806500,8.727833,8.380000,8.068667